<!-- Page d'accueil -->
<h2><i class="fa fa-home"></i> Accueil</h2>
<?php if (!empty($_SESSION) and $_SESSION['user']['name'] !== 'foo') : ?>
    <nav>
        <a href="<?= $path ?>controllers/add_post.php">Rédiger un nouvel article</a>
    </nav>
<?php endif; ?>
<!-- Liste des articles du blog -->
<ul class="post-list">
    <?php foreach($posts as $post): ?>
        <li class="post">
            <article>
                <h3>
                    <i class="fa fa-hand-o-right"></i>&nbsp;
                    <!-- Lien vers article de blog détaillé avec les commentaires -->
                    <a href="<?= $path ?>controllers/show_post.php?id=<?= intval($post['Id']) ?>" title="Consulter l'article">
                        <?= htmlspecialchars($post['Title']) ?>
                    </a>
                </h3>
                <!-- Seul un extrait de l'article du blog est affiché -->
                <?= substr(htmlspecialchars($post['Contents']), 0, 100) ?>&nbsp;[...]
                <small>
                    Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
                    le <?= htmlspecialchars($post['CreationTimestamp']) ?>
                </small>
            </article>
        </li>
    <?php endforeach; ?>
</ul>