<!-- Page d'article de blog détaillé avec les commentaires -->
<h2><i class="fa fa-file-text-o"></i> Article</h2>

<!-- Article du blog -->
<section class="post">
    <h3><?= htmlspecialchars($post['Title']) ?></h3>
    <article><?= nl2br(htmlspecialchars($post['Contents'])) ?></article>
    <small>
        Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
        le <?= htmlspecialchars($post['CreationTimestamp']) ?>
    </small>
</section>

<hr>

<!-- Liste des commentaires de l'article du blog -->
<ul class="comment-list">
    <?php foreach($comments as $comment): ?>
        <li class="comment">
            <h4><i class="fa fa-comment"></i> Rédigé par <?= htmlspecialchars($comment['NickName']) ?></h4>
            <article><?= htmlspecialchars($comment['Contents']) ?></article>
        </li>
    <?php endforeach; ?>
</ul>

<hr>

<!-- Formulaire de saisie d'un nouveau commentaire pour cet article -->
<form class="ui form" action="../controllers/add_comment.php" method="POST">

    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->
    <input type="hidden" name="postId" value="<?= intval($_GET['id']) ?>">

    <fieldset>
        <legend><i class="fa fa-comment-o"></i> Nouveau commentaire</legend>
        <div class="ui form">
            <div class="field">
                <label>Pseudo</label>
                <input type="text" name="nickName">
            </div>
        </div>
        <div class="ui form">
            <div class="field">
                <label>Votre Commentaire</label>
                <textarea name="contents" rows="5"></textarea>
            </div>
        </div>
        <button class="ui button" type="submit">Enregistrer</button>
        <button type="reset" class="negative ui button">Annuler</button>
    </fieldset>
</form>